### ISSUE TITLE
Point at the new fork of jsonschema2md

### ISSUE THREAD

**Issue by brynpickering** [conda-forge/jsonschema2md-feedstock#1]
### Comment:

[jsonschema2md](https://github.com/RalfG/jsonschema2md) has been archived in favour of [a fork](https://github.com/sbrunner/jsonschema2md) which is indexed on PyPI as [jsonschema2md2](https://pypi.org/project/jsonschema2md2/). It would be great if this feedstock could point to the new fork and continue to release conda-forge versions of `jsonschema2md` >= v0.4.0.

@sbrunner - would you be able to take over maintenance of this channel?

**Comment by sbrunner** [comment]
On pypi the booth packages `jsonschema2md2` and `jsonschema2md` are maintained and the prefers one is `jsonschema2md`.
